version: '3.0'
services:
  postgres:
    image: postgres:12.4
    ports:
        - "${REVDEBUG_MONITOR_PORT:-5433}:5432"
    volumes:
        - /srv/pgsql_invoices:/var/lib/postgresql/data
    environment:
            POSTGRES_USER: ${REVDEBUG_POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            POSTGRES_DB: ${REVDEBUG_POSTGRES_DATABASE:-Invoices }
  discounter:
    build: ./Discounter
  assembler:
    build: ./InvoiceAssembler
    environment:
            ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: RevDeBugAPM.Agent.AspNetCore
            JAVA_INVOICE_ADDRESS: http://processor.invoices:8082
            PYTHON_INVOICE_ADDRESS: http://processor.invoices:8083
            INVOICE_LANGUAGE: ${INVOICE_LANGUAGE:-java}
    links:
        - "python:python.invoices"
        - "nodejs:nodejs.invoices"
        - "processor:processor.invoices"
        - "postgres:postgres.invoices"
  sender:
    build: ./InvoiceSender
    environment:
            ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: RevDeBugAPM.Agent.AspNetCore
  viewer:
    build: ./InvoiceCore
    environment:
            ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: RevDeBugAPM.Agent.AspNetCore
            ASSEMBLER_ADDRESS: http://assembler.invoices:5100
            DISCOUNTER_ADDRESS: http://discounter.invoices:5200
    ports:
        - 6012:5400
    links:
        - "assembler:assembler.invoices"
        - "discounter:discounter.invoices"
  processor:
    build: ./InvoiceJava
    links:
        - "sender:sender.invoices"
        - "postgres:postgres.invoices"
    ports:
        - 6013:8082
    environment:
            SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/Invoices
            SPRING.DATASOURCE.USERNAME: postgres
            SPRING.DATASOURCE.PASSWORD: masterkey
            InvoicesCoreAddress: http://demo-apps.revdebug.com:6012
            InvoicesSenderAddress: http://sender.invoices:5300
            SW_AGENT_COLLECTOR_BACKEND_SERVICES: 127.0.0.1:11800
  python:
    build: ./InvoicePython
    links:
        - "sender:sender.invoices"
        - "postgres:postgres.invoices"
    environment:
            REVDEBUG_APPLICATIONS_HOST: ${REVDEBUG_APPLICATIONS_HOST:-51.103.82.86}
            REVDEBUG_MODE: crash
            REVDEBUG_SOLUTION: ${REVDEBUG_SOLUTION:-Python_invoices}
            InvoicesSenderAddress: http://sender.invoices:5300
            REVDEBUG_RELEASE: ${REVDEBUG_RELEASE:-1a9431ec31989e09b058ab386cc5d799d481e75a}
            REVDEBUG_APM: 1
    ports:
        - 6011:8083
  nodejs:
    build: ./InvoiceNodejs
    links:
        - "sender:sender.invoices"
        - "postgres:postgres.invoices"
    environment:
            REVDEBUG_APPLICATIONS_HOST: ${REVDEBUG_APPLICATIONS_HOST:-51.103.82.86}
            REVDEBUG_MODE: crash
            REVDEBUG_SOLUTION: ${REVDEBUG_SOLUTION:-Nodejs_invoices}
            InvoicesSenderAddress: http://sender.invoices:5300
            REVDEBUG_RELEASE: ${REVDEBUG_RELEASE:-1a9431ec31989e09b058ab386cc5d799d481e75a}
            REVDEBUG_APM: 1
    ports:
        - 6010:8081